# -*- coding: utf-8 -*-

ACADEMY_TESTS_ATTEMPT_RESUME_HELPER = '''
SELECT
    academy_tests_attempt.ID,
    academy_tests_attempt.ID AS attempt_id,
    academy_tests_attempt.active,
    academy_tests_attempt.answer_count,
    academy_tests_attempt.answered_count,
    academy_tests_attempt.answered_percent,
    academy_tests_attempt.assignment_id,
    academy_tests_attempt.available_time,
    academy_tests_attempt.blank,
    academy_tests_attempt.blank_count,
    academy_tests_attempt.blank_percent,
    academy_tests_attempt.blank_points,
    academy_tests_attempt.blank_score,
    academy_tests_attempt.time_by,
    academy_tests_attempt.description,
    academy_tests_attempt.doubt_count,
    academy_tests_attempt.elapsed,
    academy_tests_attempt."end",
    academy_tests_attempt.enrolment_id,
    academy_tests_attempt.final_points,
    academy_tests_attempt.final_score,
    academy_tests_attempt.grade,
    academy_tests_attempt.individual_id,
    academy_tests_attempt.lock_time,
    academy_tests_attempt.max_points,
    academy_tests_attempt.passed,
    academy_tests_attempt.question_count,
    academy_tests_attempt.RANK,
    academy_tests_attempt.rating,
    academy_tests_attempt."right",
    academy_tests_attempt.right_count,
    academy_tests_attempt.right_percent,
    academy_tests_attempt.right_points,
    academy_tests_attempt.right_score,
    academy_tests_attempt.START,
    academy_tests_attempt.student_id,
    academy_tests_attempt.test_id,
    academy_tests_attempt.wrong,
    academy_tests_attempt.wrong_count,
    academy_tests_attempt.wrong_percent,
    academy_tests_attempt.wrong_points,
    academy_tests_attempt.wrong_score
FROM
    academy_tests_attempt
WHERE
    academy_tests_attempt.active
'''
